/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/groups/{id}/competence-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kompetenzstufenverteilung in der Lerngruppe */
        get: operations["getGroupCompetenceLevels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lösungshäufigkeiten je Item in der Lerngruppe */
        get: operations["getGroupItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{id}/aggregations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregierte Werte (z.B. Lösungshäufigkeiten) in der Lerngruppe */
        get: operations["getGroupAggregations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools/{id}/competence-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kompetenzstufenverteilung an der Schule */
        get: operations["getSchoolCompetenceLevels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lösungshäufigkeiten je Item an der Schule */
        get: operations["getSchoolItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schools/{id}/aggregations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregierte Werte (z.B. Lösungshäufigkeiten) an der Schule */
        get: operations["getSchoolAggregations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/states/{id}/competence-levels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kompetenzstufenverteilung im Bundesland */
        get: operations["getStateCompetenceLevels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/states/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lösungshäufigkeiten je Item im Bundesland */
        get: operations["getStateItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/states/{id}/aggregations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aggregierte Werte (z.B. Lösungshäufigkeiten) im Bundesland */
        get: operations["getStateAggregations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        domain: {
            /** @example 4ddfdc3e-79fd-47be-bbc0-341f403ac5db */
            id?: string;
            /**
             * @description Name der Domäne
             * @example Rechtschreibung
             * @example Leseverstehen
             */
            name: string;
        };
        subject: {
            /** @example 4ddfdc3e-79fd-47be-bbc0-341f403ac5db */
            id?: string;
            /**
             * @description Name des Fachs
             * @example Deutsch
             * @example Mathematik
             */
            name: string;
        };
        characteristic: {
            /**
             * @description Type of characteristic
             * @example languageAtHome
             * @example gender
             * @example SES
             * @example schoolType
             */
            type: string;
            /**
             * @description Label for the characteristic
             * @example Sprache zu Hause
             * @example Geschlecht
             * @example Sozioökonomischer Status
             * @example Schulart
             */
            label?: string;
            /**
             * @description Specific value of the characteristic
             * @example german
             * @example male
             * @example low
             * @example gymnasium
             */
            value: string;
        };
        /** @description Kovariaten der Testgruppe */
        covariates: components["schemas"]["characteristic"][];
        "value-group": {
            /** @example 32fbeb80-224a-4d13-a23c-0eec6c0d3ea7 */
            id?: string;
            /**
             * @description Art der Wertegruppe, z.B. `group`, `student`, `school`
             * @example group
             * @example student
             * @example school
             */
            type?: string;
            /**
             * @description Bezeichnung der Wertegruppe
             * @example Klasse 8a
             * @example Schüler 1
             * @example Korrigierter Landesmittelwert
             */
            name: string;
            /** @description Domäne der Wertegruppe (optional) */
            domain?: components["schemas"]["domain"];
            /** @description Fach der Wertegruppe (optional) */
            subject?: components["schemas"]["subject"];
            /** @description Kovariaten der Wertegruppe */
            covariates?: components["schemas"]["covariates"];
            /** @description Liste von Key-Value-Werten mit zusätzlichen Informationen, z.B. Testdauer, andere systemspezifische Attribute */
            properties?: {
                key: string;
                value: string;
            }[];
        };
        "competence-level": {
            /** @example 18488a76-0cb6-4d16-9f7b-d2c69f73e058 */
            id?: string;
            /**
             * @description Name der Komptenzstufe
             * @example Optimalstandard
             * @example Regularstandard
             */
            name?: string;
            /**
             * @description Kürzel der Kompetenzstufe
             * @example V
             * @example Ia
             * @example A2.1
             */
            nameShort: string;
            /**
             * @description Beschreibung der Kompetenzstufe
             * @example Kann Aussagen zu zentralen Aspekten des Textes selbstständig begründen
             */
            description?: string;
            /**
             * @description Zuordnung der Kompetenzstufe zu einem Bildungsstandard. Über Stufensets (z.B. HSA und MSA) hinweg vergleichbar, während die Stufen selbst es nicht sind.
             * @enum {string}
             */
            classification?: "unter Mindeststandard" | "Mindeststandard" | "Regelstandard" | "Regelstandard plus" | "Optimalstandard";
        };
        "competence-level-descriptive-statistics": {
            descriptiveStatistics: {
                /**
                 * @description Gesamtzahl der Schüler:innen in der Wertegruppe
                 * @example 4
                 */
                total: number;
                /**
                 * @description Anteil der Schüler:innen an der Gesamtzahl, die diese Kompetenzstufe erreicht haben.
                 * @example 0.75
                 */
                mean: number;
                /**
                 * @description Anzahl der Schüler:innen, die diese Kompetenzstufe erreicht haben.
                 * @example 3
                 */
                frequency: number;
            };
        };
        /** @description Kompetenzstufenverteilung in der Wertegruppe */
        "competence-level-statistics": (components["schemas"]["competence-level"] & components["schemas"]["competence-level-descriptive-statistics"])[];
        "competence-levels": (components["schemas"]["value-group"] & {
            competenceLevels: components["schemas"]["competence-level-statistics"];
        })[];
        exercise: {
            /** @example 4ddfdc3e-79fd-47be-bbc0-341f403ac5db */
            id?: string;
            /**
             * @description Name der Aufgabe
             * @example At the Summer Camp
             */
            name: string;
        };
        competence: {
            /** @example 4ddfdc3e-79fd-47be-bbc0-341f403ac5db */
            id?: string;
            /**
             * @description Art der Kompetenz
             * @example Kompetenz
             * @example Leitidee
             * @example Allgemeine Kompetenz
             */
            type?: string;
            /**
             * @description Name der Kompetenz
             * @example 2.5.1
             * @example L1
             */
            name?: string;
            /**
             * @description Beschreibung der Kompetenz
             * @example Richtig schreiben
             * @example Leitidee Zahl
             */
            description?: string;
        };
        /** @description (importierte) Itemparameter aus den Itemkennwerten des IQB. Bisher unvollständige, exemplarische Liste. */
        "item-parameters": {
            /** @description Schwierigkeit des Items in Logit */
            logit?: number;
            /** @description Schwierigkeit des Items in Punkten nach deutscher Bildungsstandardmetrik */
            bistaPoints?: number;
            /** @description Mittlere Lösungshäufigkeit der Pilotierung an Gymnasien */
            solutionFrequencyGymnasium?: number;
            /** @description Mittlere Lösungshäufigkeit der Pilotierung an Nicht-Gymnasien */
            solutionFrequencyNonGymnasium?: number;
            /** @description Mittlere Lösungshäufigkeit der Pilotierung an Grundschulen */
            solutionFrequencyPrimarySchool?: number;
            /** @description Fach des Items */
            subject?: string;
            /** @description Kompetenzbereich des Items */
            domain?: string;
            /** @description Kompetenzstufe des Items */
            competenceLevel?: components["schemas"]["competence-level"];
            /** @description Liste der dem Item zugeordneten Kompetenzen */
            competences?: components["schemas"]["competence"][];
        };
        item: {
            /** @example b8d23653-3881-40de-a45a-d34e2dd191ed */
            id?: string;
            /**
             * @description Bezeichnung des Items im Testheft (oft die Fragennummer)
             * @example 2.1
             * @example 2.2
             */
            name: string;
            /**
             * @description Position des Items im Testheft
             * @example 1
             * @example 2
             */
            position?: number;
            /**
             * @description IQB Item-Id des Items
             * @example AB1021
             * @example AB1022
             */
            iqbId: string;
            /** @description Aufgabe, der das Item zugeordnet ist */
            exercise: components["schemas"]["exercise"];
            /** @description Itemkennwerte des IQB für das Item */
            parameters?: components["schemas"]["item-parameters"];
        };
        "descriptive-statistics": {
            descriptiveStatistics: {
                /**
                 * @description Gesamtzahl der Items
                 * @example 4
                 */
                total: number;
                /**
                 * @description Anteil richtig gelöster Items / Mittlere Lösungsquote
                 * @example 0.75
                 */
                mean: number;
                /**
                 * @description Absolute Anzahl richtig gelöster Items
                 * @example 3
                 */
                frequency: number;
                /** @description Standardabweichung der mittleren Lösungsquote */
                standardDeviation: number;
            };
        };
        /** @description Statistiken für einzelne Items in der Wertegruppe */
        "item-statistics": (components["schemas"]["item"] & components["schemas"]["descriptive-statistics"])[];
        items: (components["schemas"]["value-group"] & {
            items: components["schemas"]["item-statistics"];
        })[];
        aggregation: {
            /**
             * @description Aggregationsart (z.B. Kompetenzstandard, Aufgabe), eigene Aggregationsarten können definiert werden.
             * @example competences
             * @example exercise
             * @example gender
             * @example domain
             * @example languageAtHome
             * @example ses
             * @example students-by-gender
             * @example students-by-languageAtHome
             * @example students-by-ses
             * @example students-by-participation
             * @example groups-by-participation
             * @example schools-by-participation
             * @example authorities-by-participation
             */
            type: string;
            /**
             * @description Einzelne aggregierte Gruppe, z.B. der Aufgabenname, die Bezeichnung der Kompetenz, ...
             * @example 2.5.3
             */
            value: string;
            /** @description Liste von IQB ItemIds, die in der Berechnung der Aggregation berücksichtigt wurden. */
            includedIqbIds?: string[];
            /**
             * @description Klartext zur aggregierten Gruppe, z.B. die Beschreibung der Teilkompetenz oder die Bezeichnung einer Merkmalsausprägung.
             * @example Richtig schreiben
             * @example weiblich
             */
            description?: string;
        };
        aggregations: (components["schemas"]["value-group"] & {
            /** @description Einzelne Aggregationen */
            aggregations: (components["schemas"]["aggregation"] & components["schemas"]["descriptive-statistics"])[];
        })[];
    };
    responses: never;
    parameters: {
        /** @description Id der Lerngruppe */
        groupId: string;
        /** @description Wertegruppen, welche ausgegeben werden sollen */
        type: string;
        /** @description Filter für bestimmte Vergleichsgruppen, die ausgegeben werden sollen. */
        comparison: string;
        /** @description Aggregationsarten, die berechnet werden sollen. Lösungsquoten laufen unter den Merkmalsnamen (`competence`, `exercise`, `domain`, `gender`, `languageAtHome`, `ses`), Kopfzahlen (Zusammensetzung) unter `<gezählte Einheit>-by-<Merkmal>` (`students-by-gender`, `students-by-languageAtHome`, `students-by-ses`, `students-by-participation`; Einheiten-Kopfzahlen `groups-by-participation`, `schools-by-participation`, `authorities-by-participation`). */
        aggregation: string;
        /** @description Id der Schule */
        schoolId: string;
        /** @description Id des Bundeslandes */
        stateId: string;
        /** @description Einschränkung der Antwort ohne neuen Pfad, kommasepariert. Vorgeschlagene Schlüssel: `authority:<id>`, `school:<id>` (auf /states), `student-<id>` (auf /groups), `run:<kennung>` (Durchgang). Nicht unterstützte Filter beantwortet ein Backend mit 501. */
        filter: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getGroupCompetenceLevels: {
        parameters: {
            query?: {
                /** @description Wertegruppen, welche ausgegeben werden sollen */
                type?: components["parameters"]["type"];
                /** @description Filter für bestimmte Vergleichsgruppen, die ausgegeben werden sollen. */
                comparison?: components["parameters"]["comparison"];
                /** @description Einschränkung der Antwort ohne neuen Pfad, kommasepariert. Vorgeschlagene Schlüssel: `authority:<id>`, `school:<id>` (auf /states), `student-<id>` (auf /groups), `run:<kennung>` (Durchgang). Nicht unterstützte Filter beantwortet ein Backend mit 501. */
                filter?: components["parameters"]["filter"];
            };
            header?: never;
            path: {
                /** @description Id der Lerngruppe */
                id: components["parameters"]["groupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kompetenzstufenverteilung in der Lerngruppe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["competence-levels"];
                };
            };
            /** @description Ungültige Anfrage, z.B. ungültige Werte für die Parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lerngruppe oder Kompetenzstufenverteilung für die Lerngruppe nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGroupItems: {
        parameters: {
            query?: {
                /** @description Wertegruppen, welche ausgegeben werden sollen */
                type?: components["parameters"]["type"];
                /** @description Filter für bestimmte Vergleichsgruppen, die ausgegeben werden sollen. */
                comparison?: components["parameters"]["comparison"];
                /** @description Einschränkung der Antwort ohne neuen Pfad, kommasepariert. Vorgeschlagene Schlüssel: `authority:<id>`, `school:<id>` (auf /states), `student-<id>` (auf /groups), `run:<kennung>` (Durchgang). Nicht unterstützte Filter beantwortet ein Backend mit 501. */
                filter?: components["parameters"]["filter"];
            };
            header?: never;
            path: {
                /** @description Id der Lerngruppe */
                id: components["parameters"]["groupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lösungshäufigkeiten je Item in der Lerngruppe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["items"];
                };
            };
            /** @description Ungültige Anfrage, z.B. ungültige Werte für die Parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lerngruppe oder Lösungshäufigkeiten für die Lerngruppe nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getGroupAggregations: {
        parameters: {
            query?: {
                /** @description Wertegruppen, welche ausgegeben werden sollen */
                type?: components["parameters"]["type"];
                /** @description Aggregationsarten, die berechnet werden sollen. Lösungsquoten laufen unter den Merkmalsnamen (`competence`, `exercise`, `domain`, `gender`, `languageAtHome`, `ses`), Kopfzahlen (Zusammensetzung) unter `<gezählte Einheit>-by-<Merkmal>` (`students-by-gender`, `students-by-languageAtHome`, `students-by-ses`, `students-by-participation`; Einheiten-Kopfzahlen `groups-by-participation`, `schools-by-participation`, `authorities-by-participation`). */
                aggregation?: components["parameters"]["aggregation"];
                /** @description Filter für bestimmte Vergleichsgruppen, die ausgegeben werden sollen. */
                comparison?: components["parameters"]["comparison"];
                /** @description Einschränkung der Antwort ohne neuen Pfad, kommasepariert. Vorgeschlagene Schlüssel: `authority:<id>`, `school:<id>` (auf /states), `student-<id>` (auf /groups), `run:<kennung>` (Durchgang). Nicht unterstützte Filter beantwortet ein Backend mit 501. */
                filter?: components["parameters"]["filter"];
            };
            header?: never;
            path: {
                /** @description Id der Lerngruppe */
                id: components["parameters"]["groupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Abhängig vom Typ berechnete Aggregation für die Lerngruppe */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["aggregations"];
                };
            };
            /** @description Ungültige Anfrage, z.B. ungültige Werte für die Parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lerngruppe oder Werte für die Lerngruppe nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSchoolCompetenceLevels: {
        parameters: {
            query?: {
                /** @description Wertegruppen, welche ausgegeben werden sollen */
                type?: components["parameters"]["type"];
                /** @description Filter für bestimmte Vergleichsgruppen, die ausgegeben werden sollen. */
                comparison?: components["parameters"]["comparison"];
                /** @description Einschränkung der Antwort ohne neuen Pfad, kommasepariert. Vorgeschlagene Schlüssel: `authority:<id>`, `school:<id>` (auf /states), `student-<id>` (auf /groups), `run:<kennung>` (Durchgang). Nicht unterstützte Filter beantwortet ein Backend mit 501. */
                filter?: components["parameters"]["filter"];
            };
            header?: never;
            path: {
                /** @description Id der Schule */
                id: components["parameters"]["schoolId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kompetenzstufenverteilung an der Schule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["competence-levels"];
                };
            };
            /** @description Ungültige Anfrage, z.B. ungültige Werte für die Parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Schule oder Kompetensstufenverteilung für die Schule nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSchoolItems: {
        parameters: {
            query?: {
                /** @description Wertegruppen, welche ausgegeben werden sollen */
                type?: components["parameters"]["type"];
                /** @description Filter für bestimmte Vergleichsgruppen, die ausgegeben werden sollen. */
                comparison?: components["parameters"]["comparison"];
                /** @description Einschränkung der Antwort ohne neuen Pfad, kommasepariert. Vorgeschlagene Schlüssel: `authority:<id>`, `school:<id>` (auf /states), `student-<id>` (auf /groups), `run:<kennung>` (Durchgang). Nicht unterstützte Filter beantwortet ein Backend mit 501. */
                filter?: components["parameters"]["filter"];
            };
            header?: never;
            path: {
                /** @description Id der Schule */
                id: components["parameters"]["schoolId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lösungshäufigkeiten je Item an der Schule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["items"];
                };
            };
            /** @description Ungültige Anfrage, z.B. ungültige Werte für die Parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Schule oder Lösungshäufigkeit je Item für die Schule nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getSchoolAggregations: {
        parameters: {
            query?: {
                /** @description Wertegruppen, welche ausgegeben werden sollen */
                type?: components["parameters"]["type"];
                /** @description Aggregationsarten, die berechnet werden sollen. Lösungsquoten laufen unter den Merkmalsnamen (`competence`, `exercise`, `domain`, `gender`, `languageAtHome`, `ses`), Kopfzahlen (Zusammensetzung) unter `<gezählte Einheit>-by-<Merkmal>` (`students-by-gender`, `students-by-languageAtHome`, `students-by-ses`, `students-by-participation`; Einheiten-Kopfzahlen `groups-by-participation`, `schools-by-participation`, `authorities-by-participation`). */
                aggregation?: components["parameters"]["aggregation"];
                /** @description Filter für bestimmte Vergleichsgruppen, die ausgegeben werden sollen. */
                comparison?: components["parameters"]["comparison"];
                /** @description Einschränkung der Antwort ohne neuen Pfad, kommasepariert. Vorgeschlagene Schlüssel: `authority:<id>`, `school:<id>` (auf /states), `student-<id>` (auf /groups), `run:<kennung>` (Durchgang). Nicht unterstützte Filter beantwortet ein Backend mit 501. */
                filter?: components["parameters"]["filter"];
            };
            header?: never;
            path: {
                /** @description Id der Schule */
                id: components["parameters"]["schoolId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Abhängig vom Typ berechnete Aggregation für die Schule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["aggregations"];
                };
            };
            /** @description Ungültige Anfrage, z.B. ungültige Werte für die Parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Schule oder Werte für die Schule nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStateCompetenceLevels: {
        parameters: {
            query?: {
                /** @description Wertegruppen, welche ausgegeben werden sollen */
                type?: components["parameters"]["type"];
                /** @description Filter für bestimmte Vergleichsgruppen, die ausgegeben werden sollen. */
                comparison?: components["parameters"]["comparison"];
                /** @description Einschränkung der Antwort ohne neuen Pfad, kommasepariert. Vorgeschlagene Schlüssel: `authority:<id>`, `school:<id>` (auf /states), `student-<id>` (auf /groups), `run:<kennung>` (Durchgang). Nicht unterstützte Filter beantwortet ein Backend mit 501. */
                filter?: components["parameters"]["filter"];
            };
            header?: never;
            path: {
                /** @description Id des Bundeslandes */
                id: components["parameters"]["stateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kompetenzstufenverteilung im Bundesland */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["competence-levels"];
                };
            };
            /** @description Ungültige Anfrage, z.B. ungültige Werte für die Parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bundesland oder Kompetensstufenverteilung für das Bundesland nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStateItems: {
        parameters: {
            query?: {
                /** @description Wertegruppen, welche ausgegeben werden sollen */
                type?: components["parameters"]["type"];
                /** @description Filter für bestimmte Vergleichsgruppen, die ausgegeben werden sollen. */
                comparison?: components["parameters"]["comparison"];
                /** @description Einschränkung der Antwort ohne neuen Pfad, kommasepariert. Vorgeschlagene Schlüssel: `authority:<id>`, `school:<id>` (auf /states), `student-<id>` (auf /groups), `run:<kennung>` (Durchgang). Nicht unterstützte Filter beantwortet ein Backend mit 501. */
                filter?: components["parameters"]["filter"];
            };
            header?: never;
            path: {
                /** @description Id des Bundeslandes */
                id: components["parameters"]["stateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lösungshäufigkeiten je Item im Bundesland */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["items"];
                };
            };
            /** @description Ungültige Anfrage, z.B. ungültige Werte für die Parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bundesland oder Lösungshäufigkeit je Item für das Bundesland nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getStateAggregations: {
        parameters: {
            query?: {
                /** @description Wertegruppen, welche ausgegeben werden sollen */
                type?: components["parameters"]["type"];
                /** @description Aggregationsarten, die berechnet werden sollen. Lösungsquoten laufen unter den Merkmalsnamen (`competence`, `exercise`, `domain`, `gender`, `languageAtHome`, `ses`), Kopfzahlen (Zusammensetzung) unter `<gezählte Einheit>-by-<Merkmal>` (`students-by-gender`, `students-by-languageAtHome`, `students-by-ses`, `students-by-participation`; Einheiten-Kopfzahlen `groups-by-participation`, `schools-by-participation`, `authorities-by-participation`). */
                aggregation?: components["parameters"]["aggregation"];
                /** @description Filter für bestimmte Vergleichsgruppen, die ausgegeben werden sollen. */
                comparison?: components["parameters"]["comparison"];
                /** @description Einschränkung der Antwort ohne neuen Pfad, kommasepariert. Vorgeschlagene Schlüssel: `authority:<id>`, `school:<id>` (auf /states), `student-<id>` (auf /groups), `run:<kennung>` (Durchgang). Nicht unterstützte Filter beantwortet ein Backend mit 501. */
                filter?: components["parameters"]["filter"];
            };
            header?: never;
            path: {
                /** @description Id des Bundeslandes */
                id: components["parameters"]["stateId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Abhängig vom Typ berechnete Aggregation für das Bundesland */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["aggregations"];
                };
            };
            /** @description Ungültige Anfrage, z.B. ungültige Werte für die Parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bundesland oder Werte für das Bundesland nicht gefunden */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
